### ISSUE TITLE
PCB Layout for ADC Converter circuitry

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/fossasia-gci15#45]
AD7173 IC and related component placement and routing

**Comment by tharaka27** [comment]
Hey, a little questions.. why are you guys using AD7173 IC rather than  ADS1299 ?

**Comment by CloudyPadmal** [comment]
Hi, There are quiet a few reasons;
1. Price (AD7173 < $17 | ADS1299 < $30) There is an alternative suggested in #55 for AD7173 replacing it with an IC of similar specs
2. Dimensions (though it could be tolerable)
3. NeuroLab is targeted for hobbyists. So we don't require medical grade quality readings.
